package Section1;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

public class xpath_Scenario4 
{
	
	public static void main(String[] args) throws Exception 
	{
		System.setProperty("webdriver.chrome.driver", "E:\\selenium\\chromedriver-win64\\chromedriver.exe");
		WebDriver driver=new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("https://www.flipkart.com/");
		Thread.sleep(3000);
		WebElement element=driver.findElement(By.xpath("//input[@class='Pke_EE']"));
		element.sendKeys("i phone 14");
		element.submit();
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 (Blue, 128 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 (Midnight, 256 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 (Starlight, 256 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 ((PRODUCT)RED, 512 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 (Purple, 256 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 ((PRODUCT)RED, 128 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 (Purple, 512 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 (Purple, 128 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 (Midnight, 128 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 (Starlight, 128 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 (Midnight, 512 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 (Blue, 512 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 (Starlight, 512 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 (Blue, 256 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 (Yellow, 512 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 (Yellow, 128 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 ((PRODUCT)RED, 256 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 (Yellow, 256 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 Plus (Starlight, 128 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 Plus (Midnight, 128 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 Plus (Blue, 128 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 (Starlight, 256 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 ((PRODUCT)RED, 512 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 (Purple, 256 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 ((PRODUCT)RED, 128 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 (Purple, 512 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 (Purple, 128 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 (Midnight, 128 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 (Starlight, 128 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 (Midnight, 512 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 (Blue, 512 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 (Starlight, 512 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text='Apple iPhone 14 (Blue, 256 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 (Yellow, 512 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 (Yellow, 128 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 ((PRODUCT)RED, 256 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 (Yellow, 256 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 Plus (Starlight, 128 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 Plus (Midnight, 128 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 Plus (Blue, 128 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 Plus (Purple, 128 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 Plus ((PRODUCT)RED, 128 GB)']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//div[text()='Apple iPhone 14 Plus (Yellow, 128 GB)']")).click();
		driver.quit();
	}
}
